// <auto-generated />
using ClashRoyaleBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Service.Migrations
{
    [DbContext(typeof(ClsshRoyaleContext))]
    partial class ClsshRoyaleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("ClashRoyaleBot.Clan", b =>
                {
                    b.Property<int>("ClanTag");

                    b.Property<string>("Title");

                    b.HasKey("ClanTag");

                    b.ToTable("Clans");
                });

            modelBuilder.Entity("ClashRoyaleBot.Player", b =>
                {
                    b.Property<int>("PlayerTag");

                    b.Property<int>("ClanTag");

                    b.Property<string>("Name");

                    b.HasKey("PlayerTag");

                    b.HasIndex("ClanTag");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ClashRoyaleBot.Player", b =>
                {
                    b.HasOne("ClashRoyaleBot.Clan", "Clan")
                        .WithMany("Players")
                        .HasForeignKey("ClanTag")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
